data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'Librispeech'                   # Specify corpus
    path: '/data/storage/harry/LibriSpeech'
    # train_split: ['librispeech-lm-norm.txt'] # Official LM src from LibriSpeech
    train_split: ['train-clean-100']
    dev_split: ['dev-clean']
    bucketing: True
    batch_size: 128
  text:
    mode: 'character'                     # 'character'/'word'/'subword'
    vocab_file: 'corpus/librispeech_char.txt'

hparas:                                   # Experiment hyper-parameters
  valid_step: 5000
  max_step: 100000000
  optimizer: 'Adam'
  lr: 0.0001
  eps: 0.00000001
  lr_scheduler: 'fixed'                    # 'fixed'/'warmup'

model:                                     # Model architecture
  emb_tying: False                         # https://arxiv.org/pdf/1608.05859.pdf
  emb_dim: 256
  module: 'LSTM'                           # 'LSTM'/'GRU'
  dim: 256
  n_layers: 2
  dropout: 0.5